/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as MockScrapeRouteImport } from './routes/mock-scrape'
import { Route as MockFormRouteImport } from './routes/mock-form'
import { Route as MockEmailRouteImport } from './routes/mock-email'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLocalRelaySnapshotRouteImport } from './routes/api/local-relay-snapshot'
import { Route as ApiLocalRelayShareRouteImport } from './routes/api/local-relay-share'
import { Route as ApiLocalRelayControlRouteImport } from './routes/api/local-relay-control'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MockScrapeRoute = MockScrapeRouteImport.update({
  id: '/mock-scrape',
  path: '/mock-scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const MockFormRoute = MockFormRouteImport.update({
  id: '/mock-form',
  path: '/mock-form',
  getParentRoute: () => rootRouteImport,
} as any)
const MockEmailRoute = MockEmailRouteImport.update({
  id: '/mock-email',
  path: '/mock-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalRelaySnapshotRoute = ApiLocalRelaySnapshotRouteImport.update({
  id: '/api/local-relay-snapshot',
  path: '/api/local-relay-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalRelayShareRoute = ApiLocalRelayShareRouteImport.update({
  id: '/api/local-relay-share',
  path: '/api/local-relay-share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalRelayControlRoute = ApiLocalRelayControlRouteImport.update({
  id: '/api/local-relay-control',
  path: '/api/local-relay-control',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/handoff': typeof HandoffRoute
  '/live': typeof LiveRoute
  '/mock-email': typeof MockEmailRoute
  '/mock-form': typeof MockFormRoute
  '/mock-scrape': typeof MockScrapeRoute
  '/timeline': typeof TimelineRoute
  '/api/local-relay-control': typeof ApiLocalRelayControlRoute
  '/api/local-relay-share': typeof ApiLocalRelayShareRoute
  '/api/local-relay-snapshot': typeof ApiLocalRelaySnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/handoff': typeof HandoffRoute
  '/live': typeof LiveRoute
  '/mock-email': typeof MockEmailRoute
  '/mock-form': typeof MockFormRoute
  '/mock-scrape': typeof MockScrapeRoute
  '/timeline': typeof TimelineRoute
  '/api/local-relay-control': typeof ApiLocalRelayControlRoute
  '/api/local-relay-share': typeof ApiLocalRelayShareRoute
  '/api/local-relay-snapshot': typeof ApiLocalRelaySnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/handoff': typeof HandoffRoute
  '/live': typeof LiveRoute
  '/mock-email': typeof MockEmailRoute
  '/mock-form': typeof MockFormRoute
  '/mock-scrape': typeof MockScrapeRoute
  '/timeline': typeof TimelineRoute
  '/api/local-relay-control': typeof ApiLocalRelayControlRoute
  '/api/local-relay-share': typeof ApiLocalRelayShareRoute
  '/api/local-relay-snapshot': typeof ApiLocalRelaySnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/demo'
    | '/handoff'
    | '/live'
    | '/mock-email'
    | '/mock-form'
    | '/mock-scrape'
    | '/timeline'
    | '/api/local-relay-control'
    | '/api/local-relay-share'
    | '/api/local-relay-snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/demo'
    | '/handoff'
    | '/live'
    | '/mock-email'
    | '/mock-form'
    | '/mock-scrape'
    | '/timeline'
    | '/api/local-relay-control'
    | '/api/local-relay-share'
    | '/api/local-relay-snapshot'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/demo'
    | '/handoff'
    | '/live'
    | '/mock-email'
    | '/mock-form'
    | '/mock-scrape'
    | '/timeline'
    | '/api/local-relay-control'
    | '/api/local-relay-share'
    | '/api/local-relay-snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  DemoRoute: typeof DemoRoute
  HandoffRoute: typeof HandoffRoute
  LiveRoute: typeof LiveRoute
  MockEmailRoute: typeof MockEmailRoute
  MockFormRoute: typeof MockFormRoute
  MockScrapeRoute: typeof MockScrapeRoute
  TimelineRoute: typeof TimelineRoute
  ApiLocalRelayControlRoute: typeof ApiLocalRelayControlRoute
  ApiLocalRelayShareRoute: typeof ApiLocalRelayShareRoute
  ApiLocalRelaySnapshotRoute: typeof ApiLocalRelaySnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-scrape': {
      id: '/mock-scrape'
      path: '/mock-scrape'
      fullPath: '/mock-scrape'
      preLoaderRoute: typeof MockScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-form': {
      id: '/mock-form'
      path: '/mock-form'
      fullPath: '/mock-form'
      preLoaderRoute: typeof MockFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-email': {
      id: '/mock-email'
      path: '/mock-email'
      fullPath: '/mock-email'
      preLoaderRoute: typeof MockEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-relay-snapshot': {
      id: '/api/local-relay-snapshot'
      path: '/api/local-relay-snapshot'
      fullPath: '/api/local-relay-snapshot'
      preLoaderRoute: typeof ApiLocalRelaySnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-relay-share': {
      id: '/api/local-relay-share'
      path: '/api/local-relay-share'
      fullPath: '/api/local-relay-share'
      preLoaderRoute: typeof ApiLocalRelayShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-relay-control': {
      id: '/api/local-relay-control'
      path: '/api/local-relay-control'
      fullPath: '/api/local-relay-control'
      preLoaderRoute: typeof ApiLocalRelayControlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  DemoRoute: DemoRoute,
  HandoffRoute: HandoffRoute,
  LiveRoute: LiveRoute,
  MockEmailRoute: MockEmailRoute,
  MockFormRoute: MockFormRoute,
  MockScrapeRoute: MockScrapeRoute,
  TimelineRoute: TimelineRoute,
  ApiLocalRelayControlRoute: ApiLocalRelayControlRoute,
  ApiLocalRelayShareRoute: ApiLocalRelayShareRoute,
  ApiLocalRelaySnapshotRoute: ApiLocalRelaySnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
